name = "clique"
version = "1.0.0"
target = "javascript"

description = "Create graph visualisations and node-based UIs with Lustre"
repository = { type = "github", user = "hayleigh-dot-dev", repo = "clique" }
licences = ["MIT"]

links = [
    { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

internal_modules = [ "clique/internal", "clique/internal/*" ]

[dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_stdlib = ">= 0.63.0 and < 2.0.0"
lustre = { path = "../../work/lustre-labs/lustre" }
justin = ">= 1.0.1 and < 2.0.0"
